<?php

namespace AppBundle\Repository;

/**
 * Sad2BeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Sad2BeRepository extends \Doctrine\ORM\EntityRepository
{
}
