# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    repos:
        - {org: ongr-io, repo: ElasticsearchDSL}
        - {org: ongr-io, repo: ElasticsearchBundle}
        - {org: ongr-io, repo: FilterManagerBundle}
        - {org: ongr-io, repo: RouterBundle}
        - {org: ongr-io, repo: ApiBundle}
        - {org: ongr-io, repo: TranslationsBundle}
        - {org: ongr-io, repo: CurrencyExchangeBundle}
        - {org: ongr-io, repo: CookiesBundle}
        - {org: ongr-io, repo: SettingsBundle}
    commons:
        - {title: "What is ONGR", org: ongr-io, repo: global-docs, path: WhatIsONGR.md}
        - {title: "Start with Demo app", org: ongr-io, repo: demo.ongr.io, path: README.md}
        - {title: "Contributing to ONGR", org: ongr-io, repo: global-docs, path: Contributing.md}

services:
#    app.example:
#        class: AppBundle\Service\ExampleService
#        arguments: ["@doctrine.orm.entity_manager"]
